name: Workflow Publish

on:
  workflow_call:
  push:
    branches:
      - 'main'
      - '!gh-pages'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Call-Publish :
    runs-on: ubuntu-latest
    permissions:
      contents: write  

    steps:

      # Install Java runtime (only needed if you want to run the offical HL7 Java validator)
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'    
 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
                    
      - name: Install modules
        run: npm install -g fsh-sushi@${{ env.SUSHI_VERSION }}
      - name: Run sushi
        run: sushi .
      
      # Downloads the newest version of the IG Publisher, this could probable be cached.
      - name: 📥 Download IG Publisher
        run: wget -q https://github.com/HL7/fhir-ig-publisher/releases/${{ env.IG_PUBLISHER_VERSION }}/download/publisher.jar
        
      - name: Install ruby, jekyll and graphviz        
        run: |
          sudo apt-get install ruby-full
          sudo gem install jekyll
          sudo apt-get install graphviz
      
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v4.3
      
      # Builds the HTML page for the IG.
      - name: 🏃‍♂️ Run IG Publisher
        run : java -Dfile.encoding=UTF-8 -jar publisher.jar -no-sushi -ig . -publish https://healthdatahub-france.github.io/ig/${{ steps.branch-name.outputs.current_branch }}
      
      # Publishes the HTML page to a seperate branch in order to host it using GitHub-Pages.
      # This will overwrite the currently published HTML page.
      - name: 🚀 Deploy to GitHub-Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          destination_dir: ig/${{ steps.branch-name.outputs.current_branch }}
          #exclude_assets: '**.zip,**.tgz,**.pack'
          commit_message: ' ${{ github.event.head_commit.message }}'